version: '3'

services:
  db:
    image: postgres:10.1
    ports:
      - "127.0.0.1:5432:5432"
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
